### ISSUE TITLE
Add repository field to package.json

### ISSUE THREAD

**Issue by sqs** [sourcegraph/extensions-client-common#45]
When I view an extension page like https://sourcegraph.com/extensions/slimsag/sourcegraph-discussions, I often want to go to its (git) source repository. There is no way to do that now; I need to guess at the repository name, such as by going to GitHub and looking at the most likely org that owns it. Instead, extensions' package.json should support a `repository` field that works like it does for npm packages and links to the repository's homepage, issues, etc.

![screenshot from 2018-09-17 09-06-18](https://user-images.githubusercontent.com/1976/45635094-f24fbb00-ba58-11e8-85c1-ad93bf42ff0a.png)

**Comment by chrismwendt** [comment]
Which `extension.schema.json` is canonical?

- https://sourcegraph.com/github.com/sourcegraph/extensions-client-common@83765793abe93dd0378f04f3c2b29255ce577abd/-/blob/src/schema/extension.schema.json
- https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph@ec130a9685f7c533eeb10ce336848e1d19b51b28/-/blob/schema/extension.schema.json

I'm guessing the one from e-c-c, since it looks newer. Could the other be deleted?

**Comment by sqs** [comment]
The former one is canonical.
